import { useState } from "react";
import { X, FileText, Sparkles, Download, RefreshCw, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { ServiceRequest } from "@/data/transformationOffice";
import { useToast } from "@/hooks/use-toast";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface DocWriterModalProps {
  request: ServiceRequest | null;
  isOpen: boolean;
  onClose: () => void;
  onComplete: (generatedDoc: string) => void;
}

type GenerationStage = "idle" | "analyzing" | "selecting-template" | "generating" | "complete";

export default function DocWriterModal({ request, isOpen, onClose, onComplete }: DocWriterModalProps) {
  const [generationStage, setGenerationStage] = useState<GenerationStage>("idle");
  const [progress, setProgress] = useState(0);
  const [selectedTemplate, setSelectedTemplate] = useState<string>("");
  const [additionalContext, setAdditionalContext] = useState("");
  const [generatedDocument, setGeneratedDocument] = useState("");
  const { toast } = useToast();

  if (!request || !isOpen) return null;

  const isTemplate = request.type === "dtmp-templates";
  const isSpec = request.type === "solution-specs";

  // Available templates based on request type
  const availableTemplates = isTemplate ? [
    { id: "api-integration", name: "API Integration Documentation", description: "Standard template for API integration docs" },
    { id: "security-assessment", name: "Security Assessment", description: "Security review and assessment template" },
    { id: "devops-runbook", name: "DevOps Runbook", description: "Operational runbook template" },
    { id: "architecture-decision", name: "Architecture Decision Record", description: "ADR template for technical decisions" },
    { id: "deployment-guide", name: "Deployment Guide", description: "Step-by-step deployment documentation" },
  ] : [
    { id: "ecommerce-platform", name: "E-commerce Platform Spec", description: "Complete e-commerce solution specification" },
    { id: "data-lake", name: "Data Lake Architecture", description: "Modern data lake platform specification" },
    { id: "microservices", name: "Microservices Architecture", description: "Cloud-native microservices specification" },
    { id: "event-driven", name: "Event-Driven Architecture", description: "Event-driven system specification" },
    { id: "api-gateway", name: "API Gateway Solution", description: "API gateway implementation specification" },
  ];

  const handleStartGeneration = () => {
    if (!selectedTemplate) {
      alert("Please select a template first");
      return;
    }

    // Stage 1: Analyzing requirements
    setGenerationStage("analyzing");
    setProgress(10);

    setTimeout(() => {
      setProgress(30);
      setGenerationStage("selecting-template");
      
      setTimeout(() => {
        setProgress(50);
        setGenerationStage("generating");
        
        // Simulate document generation
        setTimeout(() => {
          setProgress(100);
          setGenerationStage("complete");
          
          // Generate mock document
          const docContent = generateMockDocument();
          setGeneratedDocument(docContent);
        }, 3000);
      }, 1500);
    }, 2000);
  };

  const generateMockDocument = () => {
    const templateName = availableTemplates.find(t => t.id === selectedTemplate)?.name || "Document";
    
    if (isTemplate) {
      return `# ${templateName}

## Document Information
- **Request**: ${request.requestNumber}
- **Requester**: ${request.requester.name}
- **Organization**: ${request.requester.organization}
- **Generated**: ${new Date().toLocaleDateString()}

## Overview
${request.description}

## Purpose
This document provides a comprehensive template for ${templateName.toLowerCase()}. It includes all necessary sections, guidelines, and best practices to ensure consistency and quality.

## Sections

### 1. Introduction
Brief overview of the purpose and scope of this documentation.

### 2. Prerequisites
- Required tools and technologies
- Access requirements
- Knowledge prerequisites

### 3. Main Content
Detailed content specific to ${templateName.toLowerCase()}.

${additionalContext ? `\n### Additional Context\n${additionalContext}\n` : ''}

### 4. Best Practices
- Follow industry standards
- Maintain consistency
- Document all decisions
- Keep information up-to-date

### 5. References
- Internal documentation links
- External resources
- Related templates

## Appendix
Additional information and resources.

---
*Generated by DTMP AI DocWriter*
*Template: ${templateName}*`;
    } else {
      return `# ${request.title} - Solution Specification

## Executive Summary
This specification document outlines the complete solution architecture for ${request.title}.

**Request Details:**
- Request Number: ${request.requestNumber}
- Requester: ${request.requester.name}
- Department: ${request.requester.department}
- Organization: ${request.requester.organization}

## 1. Business Requirements

### 1.1 Overview
${request.description}

### 1.2 Objectives
- Deliver scalable and maintainable solution
- Ensure security and compliance
- Optimize for performance
- Enable future extensibility

${additionalContext ? `\n### 1.3 Additional Requirements\n${additionalContext}\n` : ''}

## 2. Solution Architecture

### 2.1 High-Level Architecture
The solution follows a modern, cloud-native architecture pattern with the following key components:

- **Frontend Layer**: React-based web application
- **API Gateway**: Kong/AWS API Gateway for request routing
- **Service Layer**: Microservices architecture
- **Data Layer**: PostgreSQL for relational data, Redis for caching
- **Integration Layer**: Event-driven messaging with Kafka

### 2.2 Technology Stack
- **Frontend**: React, TypeScript, Tailwind CSS
- **Backend**: Node.js, Express, TypeScript
- **Database**: PostgreSQL 15, Redis 7
- **Message Queue**: Apache Kafka
- **Container Orchestration**: Kubernetes
- **Cloud Provider**: AWS/Azure/GCP

### 2.3 Security Architecture
- OAuth 2.0 / OpenID Connect for authentication
- Role-based access control (RBAC)
- API rate limiting and throttling
- Data encryption at rest and in transit
- Regular security audits and penetration testing

## 3. Component Specifications

### 3.1 Frontend Application
- Responsive design for desktop and mobile
- Progressive Web App (PWA) capabilities
- Accessibility compliance (WCAG 2.1 AA)
- Performance optimization (< 3s load time)

### 3.2 Backend Services
- RESTful API design
- GraphQL for complex queries
- Microservices with clear boundaries
- Service mesh for inter-service communication

### 3.3 Data Management
- Database schema design
- Data migration strategy
- Backup and disaster recovery
- Data retention policies

## 4. Integration Points

### 4.1 External Systems
- Third-party API integrations
- Legacy system connections
- Partner system interfaces

### 4.2 Internal Systems
- Authentication service
- Notification service
- Analytics platform

## 5. Non-Functional Requirements

### 5.1 Performance
- Response time: < 200ms for 95th percentile
- Throughput: 10,000 requests per second
- Concurrent users: 50,000+

### 5.2 Scalability
- Horizontal scaling capability
- Auto-scaling based on load
- Multi-region deployment support

### 5.3 Availability
- 99.9% uptime SLA
- Zero-downtime deployments
- Disaster recovery plan

### 5.4 Compliance
- GDPR compliance
- SOC 2 Type II certification
- Industry-specific regulations

## 6. Implementation Plan

### Phase 1: Foundation (Weeks 1-4)
- Infrastructure setup
- CI/CD pipeline configuration
- Development environment setup

### Phase 2: Core Development (Weeks 5-12)
- Backend services implementation
- Frontend application development
- Integration development

### Phase 3: Testing & QA (Weeks 13-16)
- Unit testing
- Integration testing
- Performance testing
- Security testing

### Phase 4: Deployment (Weeks 17-18)
- Staging deployment
- Production deployment
- Monitoring setup

## 7. Operations & Maintenance

### 7.1 Monitoring
- Application performance monitoring (APM)
- Infrastructure monitoring
- Log aggregation and analysis
- Alerting and incident response

### 7.2 Support
- 24/7 on-call support
- Incident management process
- Change management process

## 8. Cost Estimation
- Infrastructure costs: $X,XXX/month
- Development costs: $XXX,XXX
- Operational costs: $X,XXX/month
- Total first-year cost: $XXX,XXX

## 9. Risks & Mitigation
- **Risk**: Technology complexity
  - **Mitigation**: Phased implementation, training
- **Risk**: Integration challenges
  - **Mitigation**: Early integration testing, API contracts
- **Risk**: Performance issues
  - **Mitigation**: Load testing, performance optimization

## 10. Success Metrics
- System uptime > 99.9%
- User satisfaction score > 4.5/5
- Performance targets met
- On-time delivery

---
*Generated by DTMP AI DocWriter*
*Specification Template: ${templateName}*
*Generated on: ${new Date().toLocaleString()}*`;
    }
  };

  const handleDownloadDocument = () => {
    const blob = new Blob([generatedDocument], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${request.requestNumber}-${selectedTemplate}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleRegenerateDocument = () => {
    setGenerationStage("idle");
    setProgress(0);
    setGeneratedDocument("");
  };

  const handleCompleteAndDeliver = () => {
    onComplete(generatedDocument);
    onClose();
    // Reset state
    setGenerationStage("idle");
    setProgress(0);
    setSelectedTemplate("");
    setAdditionalContext("");
    setGeneratedDocument("");
  };

  return (
    <>
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black bg-opacity-50 z-50 transition-opacity"
        onClick={generationStage === "idle" || generationStage === "complete" ? onClose : undefined}
      />

      {/* Modal */}
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-lg shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-gray-200 flex-shrink-0">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-orange-600" />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900">DTMP AI DocWriter</h2>
                <p className="text-sm text-gray-500">
                  {isTemplate ? "Template Generation" : "Specification Generation"}
                </p>
              </div>
            </div>
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              disabled={generationStage !== "idle" && generationStage !== "complete"}
            >
              <X className="w-5 h-5" />
            </Button>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6 min-h-0">
            {/* Request Information */}
            <div className="mb-6 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-sm font-semibold text-gray-900 mb-2">Request Information</h3>
              <div className="space-y-1 text-sm">
                <p><span className="text-gray-600">Request:</span> <span className="font-medium">{request.requestNumber}</span></p>
                <p><span className="text-gray-600">Title:</span> <span className="font-medium">{request.title}</span></p>
                <p><span className="text-gray-600">Requester:</span> <span className="font-medium">{request.requester.name}</span></p>
              </div>
            </div>

            {generationStage === "idle" && (
              <>
                {/* Template Selection */}
                <div className="mb-6">
                  <label className="block text-sm font-semibold text-gray-900 mb-3">
                    Select {isTemplate ? "Template" : "Specification Template"}
                  </label>
                  <Select value={selectedTemplate} onValueChange={setSelectedTemplate}>
                    <SelectTrigger>
                      <SelectValue placeholder={`Choose a ${isTemplate ? "template" : "specification template"}...`} />
                    </SelectTrigger>
                    <SelectContent>
                      {availableTemplates.map((template) => (
                        <SelectItem key={template.id} value={template.id}>
                          <div className="flex flex-col">
                            <span className="font-medium">{template.name}</span>
                            <span className="text-xs text-gray-500">{template.description}</span>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Additional Context */}
                <div className="mb-6">
                  <label className="block text-sm font-semibold text-gray-900 mb-3">
                    Additional Context (Optional)
                  </label>
                  <Textarea
                    placeholder="Add any specific requirements, preferences, or additional information..."
                    value={additionalContext}
                    onChange={(e) => setAdditionalContext(e.target.value)}
                    rows={6}
                    className="resize-none"
                  />
                  <p className="text-xs text-gray-500 mt-2">
                    Provide additional details to help AI DocWriter generate more accurate content
                  </p>
                </div>
              </>
            )}

            {(generationStage === "analyzing" || generationStage === "selecting-template" || generationStage === "generating") && (
              <div className="space-y-6">
                <div className="text-center py-8">
                  <div className="inline-flex items-center justify-center w-16 h-16 bg-orange-100 rounded-full mb-4 animate-pulse">
                    <Sparkles className="w-8 h-8 text-orange-600" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {generationStage === "analyzing" && "Analyzing Requirements..."}
                    {generationStage === "selecting-template" && "Selecting Best Template..."}
                    {generationStage === "generating" && "Generating Document..."}
                  </h3>
                  <p className="text-sm text-gray-600 mb-6">
                    {generationStage === "analyzing" && "AI is analyzing the request details and requirements"}
                    {generationStage === "selecting-template" && "Matching requirements with the optimal template"}
                    {generationStage === "generating" && "Creating comprehensive documentation based on best practices"}
                  </p>
                  <Progress value={progress} className="w-full max-w-md mx-auto" />
                  <p className="text-xs text-gray-500 mt-2">{progress}% complete</p>
                </div>
              </div>
            )}

            {generationStage === "complete" && (
              <div className="space-y-4">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Badge className="bg-green-100 text-green-700">
                      Generation Complete
                    </Badge>
                    <span className="text-sm text-gray-600">
                      {generatedDocument.split('\n').length} lines
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleDownloadDocument}
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleRegenerateDocument}
                    >
                      <RefreshCw className="w-4 h-4 mr-2" />
                      Regenerate
                    </Button>
                  </div>
                </div>

                {/* Generated Document Preview */}
                <div className="border border-gray-200 rounded-lg p-4 bg-gray-50 max-h-96 overflow-y-auto">
                  <pre className="text-xs text-gray-800 whitespace-pre-wrap font-mono">
                    {generatedDocument}
                  </pre>
                </div>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="border-t border-gray-200 p-6 bg-gray-50 flex-shrink-0">
            <div className="flex gap-3 justify-end">
              {generationStage === "idle" && (
                <>
                  <Button
                    variant="outline"
                    onClick={onClose}
                  >
                    Cancel
                  </Button>
                  <Button
                    className="bg-orange-600 hover:bg-orange-700"
                    onClick={handleStartGeneration}
                    disabled={!selectedTemplate}
                  >
                    <Sparkles className="w-4 h-4 mr-2" />
                    Generate Document
                  </Button>
                </>
              )}
              {generationStage === "complete" && (
                <>
                  <Button
                    variant="outline"
                    onClick={onClose}
                  >
                    Close
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => {
                      // Save without submitting - just close and keep status
                      toast({
                        title: "Document Saved",
                        description: "Document has been saved as draft.",
                        duration: 3000,
                      });
                      onClose();
                      // Reset state
                      setGenerationStage("idle");
                      setProgress(0);
                      setSelectedTemplate("");
                      setAdditionalContext("");
                      setGeneratedDocument("");
                    }}
                  >
                    <FileText className="w-4 h-4 mr-2" />
                    Save as Draft
                  </Button>
                  <Button
                    className="bg-green-600 hover:bg-green-700 text-white"
                    onClick={handleCompleteAndDeliver}
                  >
                    <Send className="w-4 h-4 mr-2" />
                    Submit
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
