import { X, Download, FileText, Calendar, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface DocumentPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  document: {
    id: string;
    title: string;
    type: string;
    completedDate: string;
    format: string[];
  };
}

export function DocumentPreviewModal({
  isOpen,
  onClose,
  document,
}: DocumentPreviewModalProps) {
  if (!isOpen) return null;

  const handleDownload = (format: string) => {
    console.log(`Downloading ${document.title} in ${format} format`);
    // In real implementation, this would trigger actual file download
  };

  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4"
      onClick={handleOverlayClick}
    >
      <div
        className="bg-white max-w-6xl w-full h-[90vh] rounded-2xl shadow-2xl animate-in fade-in zoom-in duration-200 relative flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5 text-purple-600" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-gray-900">{document.title}</h2>
              <div className="flex items-center gap-3 text-sm text-gray-500 mt-1">
                <span className="flex items-center gap-1">
                  <Calendar size={14} />
                  {new Date(document.completedDate).toLocaleDateString()}
                </span>
                <span>•</span>
                <Badge variant="outline" className="text-xs">
                  {document.type}
                </Badge>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {document.format.map((fmt) => (
              <Button
                key={fmt}
                variant="outline"
                size="sm"
                onClick={() => handleDownload(fmt)}
              >
                <Download className="w-4 h-4 mr-1" />
                {fmt}
              </Button>
            ))}
            <button
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-600 transition-colors rounded-lg hover:bg-gray-100"
              aria-label="Close"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Document Preview Content */}
        <div className="flex-1 overflow-auto p-8 bg-gray-50">
          <div className="max-w-4xl mx-auto bg-white shadow-lg rounded-lg p-12">
            {/* Document Header */}
            <div className="border-b-4 border-purple-600 pb-6 mb-8">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h1 className="text-3xl font-bold text-gray-900 mb-2">
                    {document.title}
                  </h1>
                  <p className="text-gray-600">
                    Generated by AI DocWriter 4.0
                  </p>
                </div>
                <div className="text-right text-sm text-gray-500">
                  <p>Document ID: {document.id}</p>
                  <p>Version: 1.0</p>
                  <p>Date: {new Date(document.completedDate).toLocaleDateString()}</p>
                </div>
              </div>
            </div>

            {/* Executive Summary */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <span className="text-purple-600">1.</span>
                Executive Summary
              </h2>
              <div className="space-y-4 text-gray-700 leading-relaxed">
                <p>
                  This document provides a comprehensive assessment of the organization's digital transformation maturity, 
                  evaluating key capabilities across technology, processes, people, and culture dimensions.
                </p>
                <p>
                  The assessment was conducted using the DBP Framework methodology, incorporating industry best practices 
                  and benchmarks to provide actionable insights and recommendations.
                </p>
                <div className="bg-blue-50 border-l-4 border-blue-600 p-4 my-6">
                  <p className="font-semibold text-blue-900 mb-2">Key Findings:</p>
                  <ul className="list-disc list-inside space-y-1 text-blue-800">
                    <li>Overall maturity score: 3.2/5.0 (Developing)</li>
                    <li>Strong foundation in cloud infrastructure</li>
                    <li>Opportunities for improvement in data governance</li>
                    <li>Recommended focus on automation and AI adoption</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Methodology */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <span className="text-purple-600">2.</span>
                Assessment Methodology
              </h2>
              <div className="space-y-4 text-gray-700 leading-relaxed">
                <p>
                  The assessment framework evaluates five key dimensions of digital maturity:
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
                  <div className="border border-gray-200 rounded-lg p-4">
                    <h3 className="font-semibold text-gray-900 mb-2">Technology</h3>
                    <p className="text-sm text-gray-600">
                      Infrastructure, platforms, and technical capabilities
                    </p>
                  </div>
                  <div className="border border-gray-200 rounded-lg p-4">
                    <h3 className="font-semibold text-gray-900 mb-2">Data & Analytics</h3>
                    <p className="text-sm text-gray-600">
                      Data management, governance, and insights
                    </p>
                  </div>
                  <div className="border border-gray-200 rounded-lg p-4">
                    <h3 className="font-semibold text-gray-900 mb-2">Processes</h3>
                    <p className="text-sm text-gray-600">
                      Automation, optimization, and agility
                    </p>
                  </div>
                  <div className="border border-gray-200 rounded-lg p-4">
                    <h3 className="font-semibold text-gray-900 mb-2">People & Culture</h3>
                    <p className="text-sm text-gray-600">
                      Skills, mindset, and organizational readiness
                    </p>
                  </div>
                </div>
              </div>
            </section>

            {/* Current State Assessment */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <span className="text-purple-600">3.</span>
                Current State Assessment
              </h2>
              <div className="space-y-6 text-gray-700 leading-relaxed">
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">3.1 Technology Infrastructure</h3>
                  <p className="mb-4">
                    The organization has made significant investments in cloud infrastructure, with 70% of workloads 
                    migrated to cloud platforms. The technology stack demonstrates good scalability and resilience.
                  </p>
                  <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                    <div className="flex justify-between items-center mb-2">
                      <span className="text-sm font-medium">Maturity Score</span>
                      <span className="text-lg font-bold text-purple-600">3.5/5.0</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div className="bg-purple-600 h-2 rounded-full" style={{ width: '70%' }}></div>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">3.2 Data & Analytics</h3>
                  <p className="mb-4">
                    Data governance practices are emerging but require formalization. Analytics capabilities are 
                    present but not fully leveraged across the organization.
                  </p>
                  <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                    <div className="flex justify-between items-center mb-2">
                      <span className="text-sm font-medium">Maturity Score</span>
                      <span className="text-lg font-bold text-yellow-600">2.8/5.0</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div className="bg-yellow-600 h-2 rounded-full" style={{ width: '56%' }}></div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Recommendations */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <span className="text-purple-600">4.</span>
                Recommendations
              </h2>
              <div className="space-y-4 text-gray-700 leading-relaxed">
                <div className="bg-green-50 border-l-4 border-green-600 p-4">
                  <h3 className="font-semibold text-green-900 mb-2">Priority 1: Data Governance Framework</h3>
                  <p className="text-green-800 text-sm">
                    Implement a comprehensive data governance framework with clear ownership, policies, and procedures.
                    Estimated timeline: 3-6 months.
                  </p>
                </div>
                <div className="bg-green-50 border-l-4 border-green-600 p-4">
                  <h3 className="font-semibold text-green-900 mb-2">Priority 2: Automation Strategy</h3>
                  <p className="text-green-800 text-sm">
                    Develop and execute an automation roadmap focusing on high-impact, repetitive processes.
                    Estimated timeline: 6-12 months.
                  </p>
                </div>
                <div className="bg-green-50 border-l-4 border-green-600 p-4">
                  <h3 className="font-semibold text-green-900 mb-2">Priority 3: Skills Development</h3>
                  <p className="text-green-800 text-sm">
                    Launch upskilling programs for data literacy, cloud technologies, and agile methodologies.
                    Estimated timeline: Ongoing.
                  </p>
                </div>
              </div>
            </section>

            {/* Conclusion */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <span className="text-purple-600">5.</span>
                Conclusion
              </h2>
              <div className="space-y-4 text-gray-700 leading-relaxed">
                <p>
                  The organization demonstrates a solid foundation for digital transformation with strong technology 
                  infrastructure and growing capabilities in key areas. By addressing the identified gaps and implementing 
                  the recommended initiatives, the organization can accelerate its digital maturity journey.
                </p>
                <p>
                  The roadmap outlined in this assessment provides a clear path forward, with prioritized actions that 
                  will deliver measurable business value and competitive advantage.
                </p>
              </div>
            </section>

            {/* Footer */}
            <div className="border-t-2 border-gray-200 pt-6 mt-12 text-sm text-gray-500">
              <div className="flex justify-between items-center">
                <div>
                  <p className="font-semibold text-gray-700">Generated by AI DocWriter 4.0</p>
                  <p>DTMP Platform • Document Studio</p>
                </div>
                <div className="text-right">
                  <p>Page 1 of 28</p>
                  <p className="text-xs">Confidential</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-gray-200 bg-gray-50">
          <p className="text-sm text-gray-600">
            This is a preview. Download the full document for complete content.
          </p>
          <div className="flex gap-2">
            <Button variant="outline" onClick={onClose}>
              Close Preview
            </Button>
            <Button 
              className="bg-purple-600 hover:bg-purple-700"
              onClick={() => handleDownload('PDF')}
            >
              <Download className="w-4 h-4 mr-2" />
              Download Full Document
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
